export const nodes = [
    {
        category: 'ConstantsAndConversions',
        codeName: 'float',
        dataType: 'float',
        description: 'Returns a constant or conversion of type float',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'int',
        dataType: 'int',
        description: 'Returns a constant or conversion of type int',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'uint',
        dataType: 'uint',
        description: 'Returns a constant or conversion of type uint',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'bool',
        dataType: 'boolean',
        description: 'Returns a constant or conversion of type boolean',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'color',
        dataType: 'color',
        description: 'Returns a constant or conversion of type color',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'vec2',
        dataType: 'vec2',
        description: 'Returns a constant or conversion of type vec2',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'vec3',
        dataType: 'vec3',
        description: 'Returns a constant or conversion of type vec3',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'vec4',
        dataType: 'vec4',
        description: 'Returns a constant or conversion of type vec4',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'mat2',
        dataType: 'mat2',
        description: 'Returns a constant or conversion of type mat2',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'mat3',
        dataType: 'mat3',
        description: 'Returns a constant or conversion of type mat3',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'mat4',
        dataType: 'mat4',
        description: 'Returns a constant or conversion of type mat4',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'ivec2',
        dataType: 'ivec2',
        description: 'Returns a constant or conversion of type ivec2',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'ivec3',
        dataType: 'ivec3',
        description: 'Returns a constant or conversion of type ivec3',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'ivec4',
        dataType: 'ivec4',
        description: 'Returns a constant or conversion of type ivec4',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'uvec2',
        dataType: 'uvec2',
        description: 'Returns a constant or conversion of type uvec2',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'uvec3',
        dataType: 'uvec3',
        description: 'Returns a constant or conversion of type uvec3',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'uvec4',
        dataType: 'uvec4',
        description: 'Returns a constant or conversion of type uvec4',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'bvec2',
        dataType: 'bvec2',
        description: 'Returns a constant or conversion of type bvec2',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'bvec3',
        dataType: 'bvec3',
        description: 'Returns a constant or conversion of type bvec3',
    },
    {
        category: 'ConstantsAndConversions',
        codeName: 'bvec4',
        dataType: 'bvec4',
        description: 'Returns a constant or conversion of type bvec4',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toFloat',
        dataType: 'float',
        description: 'Converts to float',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toInt',
        dataType: 'int',
        description: 'Converts to int',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toUint',
        dataType: 'uint',
        description: 'Converts to uint',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toBool',
        dataType: 'boolean',
        description: 'Converts to boolean',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toColor',
        dataType: 'color',
        description: 'Converts to color',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toVec2',
        dataType: 'vec2',
        description: 'Converts to vec2',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toVec3',
        dataType: 'vec3',
        description: 'Converts to vec3',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toVec4',
        dataType: 'vec4',
        description: 'Converts to vec4',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toMat2',
        dataType: 'mat2',
        description: 'Converts to mat2',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toMat3',
        dataType: 'mat3',
        description: 'Converts to mat3',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toMat4',
        dataType: 'mat4',
        description: 'Converts to mat4',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toIVec2',
        dataType: 'ivec2',
        description: 'Converts to ivec2',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toIVec3',
        dataType: 'ivec3',
        description: 'Converts to ivec3',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toIVec4',
        dataType: 'ivec4',
        description: 'Converts to ivec4',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toUVec2',
        dataType: 'uvec2',
        description: 'Converts to uvec2',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toUVec3',
        dataType: 'uvec3',
        description: 'Converts to uvec3',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toUVec4',
        dataType: 'uvec4',
        description: 'Converts to uvec4',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toBVec2',
        dataType: 'bvec2',
        description: 'Converts to bvec2',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toBVec3',
        dataType: 'bvec3',
        description: 'Converts to bvec3',
    },
    {
        category: 'MethodChainingConversions',
        codeName: 'toBVec4',
        dataType: 'bvec4',
        description: 'Converts to bvec4',
    },
    {
        category: 'Uniform',
        codeName: 'uniform',
        dataType: '',
        description: 'Creates dynamic uniform values (e.g., number, Color, Vector, Matrix).',
    },
    {
        category: 'Textures',
        codeName: 'texture',
        dataType: 'vec4',
        description: 'Sample 2D texture',
    },
    {
        category: 'Textures',
        codeName: 'cubeTexture',
        dataType: 'vec4',
        description: 'Sample cube texture',
    },
    {
        category: 'Textures',
        codeName: 'triplanarTexture',
        dataType: 'vec4',
        description: 'Triplanar mapping',
    },
    {
        category: 'Attributes',
        codeName: 'attribute',
        dataType: 'any',
        description: 'Access geometry attribute by name',
    },
    {
        category: 'Attributes',
        codeName: 'uv',
        dataType: 'vec2',
        description: 'UV attribute (index optional)',
    },
    {
        category: 'Attributes',
        codeName: 'vertexColor',
        dataType: 'color',
        description: 'Vertex color attribute',
    },
    {
        category: 'Position',
        codeName: 'positionGeometry',
        dataType: 'vec3',
        description: 'Raw position attribute',
    },
    {
        category: 'Position',
        codeName: 'positionLocal',
        dataType: 'vec3',
        description: 'Local-space position (post skinning/morph)',
    },
    {
        category: 'Position',
        codeName: 'positionWorld',
        dataType: 'vec3',
        description: 'World-space position',
    },
    {
        category: 'Position',
        codeName: 'positionWorldDirection',
        dataType: 'vec3',
        description: 'Normalized world direction',
    },
    {
        category: 'Position',
        codeName: 'positionView',
        dataType: 'vec3',
        description: 'View-space position',
    },
    {
        category: 'Position',
        codeName: 'positionViewDirection',
        dataType: 'vec3',
        description: 'Normalized view direction',
    },
    {
        category: 'Normal',
        codeName: 'normalGeometry',
        dataType: 'vec3',
        description: 'Raw normal attribute',
    },
    {
        category: 'Normal',
        codeName: 'normalLocal',
        dataType: 'vec3',
        description: 'Local-space normal',
    },
    {
        category: 'Normal',
        codeName: 'normalView',
        dataType: 'vec3',
        description: 'View-space normal',
    },
    {
        category: 'Normal',
        codeName: 'normalWorld',
        dataType: 'vec3',
        description: 'World-space normal',
    },
    {
        category: 'Normal',
        codeName: 'transformedNormalView',
        dataType: 'vec3',
        description: 'Transformed view normal (post skin/morph)',
    },
    {
        category: 'Normal',
        codeName: 'transformedNormalWorld',
        dataType: 'vec3',
        description: 'Transformed world normal',
    },
    {
        category: 'Normal',
        codeName: 'transformedClearcoatNormalView',
        dataType: 'vec3',
        description: 'Clearcoat transformed view normal',
    },
    {
        category: 'Tangent',
        codeName: 'tangentGeometry',
        dataType: 'vec4',
        description: 'Raw tangent attribute',
    },
    {
        category: 'Tangent',
        codeName: 'tangentLocal',
        dataType: 'vec3',
        description: 'Local-space tangent',
    },
    {
        category: 'Tangent',
        codeName: 'tangentView',
        dataType: 'vec3',
        description: 'View-space tangent',
    },
    {
        category: 'Tangent',
        codeName: 'tangentWorld',
        dataType: 'vec3',
        description: 'World-space tangent',
    },
    {
        category: 'Tangent',
        codeName: 'transformedTangentView',
        dataType: 'vec3',
        description: 'Transformed view tangent',
    },
    {
        category: 'Tangent',
        codeName: 'transformedTangentWorld',
        dataType: 'vec3',
        description: 'Transformed world tangent',
    },
    {
        category: 'Bitangent',
        codeName: 'bitangentGeometry',
        dataType: 'vec3',
        description: 'Geometry-space bitangent',
    },
    {
        category: 'Bitangent',
        codeName: 'bitangentLocal',
        dataType: 'vec3',
        description: 'Local-space bitangent',
    },
    {
        category: 'Bitangent',
        codeName: 'bitangentView',
        dataType: 'vec3',
        description: 'View-space bitangent',
    },
    {
        category: 'Bitangent',
        codeName: 'bitangentWorld',
        dataType: 'vec3',
        description: 'World-space bitangent',
    },
    {
        category: 'Bitangent',
        codeName: 'transformedBitangentView',
        dataType: 'vec3',
        description: 'Transformed view bitangent',
    },
    {
        category: 'Bitangent',
        codeName: 'transformedBitangentWorld',
        dataType: 'vec3',
        description: 'Transformed world bitangent',
    },
    {
        category: 'Camera',
        codeName: 'cameraNear',
        dataType: 'float',
    },
    {
        category: 'Camera',
        codeName: 'cameraFar',
        dataType: 'float',
    },
    {
        category: 'Camera',
        codeName: 'cameraProjectionMatrix',
        dataType: 'mat4',
    },
    {
        category: 'Camera',
        codeName: 'cameraProjectionMatrixInverse',
        dataType: 'mat4',
    },
    {
        category: 'Camera',
        codeName: 'cameraViewMatrix',
        dataType: 'mat4',
    },
    {
        category: 'Camera',
        codeName: 'cameraWorldMatrix',
        dataType: 'mat4',
    },
    {
        category: 'Camera',
        codeName: 'cameraNormalMatrix',
        dataType: 'mat3',
    },
    {
        category: 'Camera',
        codeName: 'cameraPosition',
        dataType: 'vec3',
    },
    {
        category: 'Model',
        codeName: 'modelDirection',
        dataType: 'vec3',
    },
    {
        category: 'Model',
        codeName: 'modelViewMatrix',
        dataType: 'mat4',
    },
    {
        category: 'Model',
        codeName: 'modelNormalMatrix',
        dataType: 'mat3',
    },
    {
        category: 'Model',
        codeName: 'modelWorldMatrix',
        dataType: 'mat4',
    },
    {
        category: 'Model',
        codeName: 'modelPosition',
        dataType: 'vec3',
    },
    {
        category: 'Model',
        codeName: 'modelScale',
        dataType: 'vec3',
    },
    {
        category: 'Model',
        codeName: 'modelViewPosition',
        dataType: 'vec3',
    },
    {
        category: 'Model',
        codeName: 'modelWorldMatrixInverse',
        dataType: 'mat4',
    },
    {
        category: 'Model',
        codeName: 'highpModelViewMatrix',
        dataType: 'mat4',
    },
    {
        category: 'Model',
        codeName: 'highpModelNormalViewMatrix',
        dataType: 'mat3',
    },
    {
        category: 'Screen',
        codeName: 'screenUV',
        dataType: 'vec2',
        description: 'Normalized framebuffer coordinate',
    },
    {
        category: 'Screen',
        codeName: 'screenCoordinate',
        dataType: 'vec2',
        description: 'Physical pixel coordinate',
    },
    {
        category: 'Screen',
        codeName: 'screentSize',
        dataType: 'vec2',
        description: 'Framebuffer size in pixels',
    },
    {
        category: 'Viewport',
        codeName: 'viewportUV',
        dataType: 'vec2',
    },
    {
        category: 'Viewport',
        codeName: 'viewport',
        dataType: 'vec4',
    },
    {
        category: 'Viewport',
        codeName: 'viewportCoordinate',
        dataType: 'vec2',
    },
    {
        category: 'Viewport',
        codeName: 'viewportSize',
        dataType: 'vec2',
    },
    {
        category: 'BlendModes',
        codeName: 'blendBurn',
        dataType: 'color',
    },
    {
        category: 'BlendModes',
        codeName: 'blendDodge',
        dataType: 'color',
    },
    {
        category: 'BlendModes',
        codeName: 'blendOverlay',
        dataType: 'color',
    },
    {
        category: 'BlendModes',
        codeName: 'blendScreen',
        dataType: 'color',
    },
    {
        category: 'BlendModes',
        codeName: 'blendColor',
        dataType: 'color',
    },
    {
        category: 'Reflect',
        codeName: 'reflectView',
        dataType: 'vec3',
    },
    {
        category: 'Reflect',
        codeName: 'reflectVector',
        dataType: 'vec3',
    },
    {
        category: 'UVUtils',
        codeName: 'matcapUV',
        dataType: 'vec2',
    },
    {
        category: 'UVUtils',
        codeName: 'rotateUV',
        dataType: 'vec2',
    },
    {
        category: 'UVUtils',
        codeName: 'spherizeUV',
        dataType: 'vec2',
    },
    {
        category: 'UVUtils',
        codeName: 'spritesheetUV',
        dataType: 'vec2',
    },
    {
        category: 'UVUtils',
        codeName: 'equirectUV',
        dataType: 'vec2',
    },
    {
        category: 'Interpolation',
        codeName: 'remap',
        dataType: 'any',
    },
    {
        category: 'Interpolation',
        codeName: 'remapClamp',
        dataType: 'any',
    },
    {
        category: 'Random',
        codeName: 'hash',
        dataType: 'float',
    },
    {
        category: 'Random',
        codeName: 'range',
        dataType: 'any',
    },
    {
        category: 'Rotate',
        codeName: 'rotate',
        dataType: 'vec2/vec3',
    },
    {
        category: 'Oscillator',
        codeName: 'oscSine',
        dataType: 'float',
    },
    {
        category: 'Oscillator',
        codeName: 'oscSquare',
        dataType: 'float',
    },
    {
        category: 'Oscillator',
        codeName: 'oscTriangle',
        dataType: 'float',
    },
    {
        category: 'Oscillator',
        codeName: 'oscSawtooth',
        dataType: 'float',
    },
    {
        category: 'Packing',
        codeName: 'directionToColor',
        dataType: 'color',
    },
    {
        category: 'Packing',
        codeName: 'colorToDirection',
        dataType: 'vec3',
    },
    {
        category: 'Operators',
        codeName: 'add',
        dataType: '',
        description: 'Addition',
    },
    {
        category: 'Operators',
        codeName: 'sub',
        dataType: '',
        description: 'Subtraction',
    },
    {
        category: 'Operators',
        codeName: 'mul',
        dataType: '',
        description: 'Multiplication',
    },
    {
        category: 'Operators',
        codeName: 'div',
        dataType: '',
        description: 'Division',
    },
    {
        category: 'Operators',
        codeName: 'assign',
        dataType: '',
        description: 'Assignment',
    },
    {
        category: 'Operators',
        codeName: 'mod',
        dataType: '',
        description: 'Modulo',
    },
    {
        category: 'Operators',
        codeName: 'equal',
        dataType: '',
        description: 'Equality comparison',
    },
    {
        category: 'Operators',
        codeName: 'notEqual',
        dataType: '',
        description: 'Inequality comparison',
    },
    {
        category: 'Operators',
        codeName: 'lessThan',
        dataType: '',
        description: 'Less than comparison',
    },
    {
        category: 'Operators',
        codeName: 'greaterThan',
        dataType: '',
        description: 'Greater than comparison',
    },
    {
        category: 'Operators',
        codeName: 'lessThanEqual',
        dataType: '',
        description: 'Less than or equal comparison',
    },
    {
        category: 'Operators',
        codeName: 'greaterThanEqual',
        dataType: '',
        description: 'Greater than or equal comparison',
    },
    {
        category: 'Operators',
        codeName: 'and',
        dataType: '',
        description: 'Logical AND',
    },
    {
        category: 'Operators',
        codeName: 'or',
        dataType: '',
        description: 'Logical OR',
    },
    {
        category: 'Operators',
        codeName: 'not',
        dataType: '',
        description: 'Logical NOT',
    },
    {
        category: 'Operators',
        codeName: 'xor',
        dataType: '',
        description: 'Logical XOR',
    },
    {
        category: 'Operators',
        codeName: 'bitAnd',
        dataType: '',
        description: 'Bitwise AND',
    },
    {
        category: 'Operators',
        codeName: 'bitNot',
        dataType: '',
        description: 'Bitwise NOT',
    },
    {
        category: 'Operators',
        codeName: 'bitOr',
        dataType: '',
        description: 'Bitwise OR',
    },
    {
        category: 'Operators',
        codeName: 'bitXor',
        dataType: '',
        description: 'Bitwise XOR',
    },
    {
        category: 'Operators',
        codeName: 'shiftLeft',
        dataType: '',
        description: 'Bit shift left',
    },
    {
        category: 'Operators',
        codeName: 'shiftRight',
        dataType: '',
        description: 'Bit shift right',
    },
    {
        category: 'Functions',
        codeName: 'Fn',
        dataType: '',
        description: 'Creates a controllable function environment (supports stack, assign, conditional).',
    },
    {
        category: 'Functions',
        codeName: 'select',
        dataType: '',
        description: 'Ternary conditional: select(condition, valueIfTrue, valueIfFalse)',
    },
    {
        category: 'Variables',
        codeName: 'toVar',
        dataType: '',
        description: 'Declares a reusable shader variable.',
    },
    {
        category: 'Variables',
        codeName: 'toConst',
        dataType: '',
        description: 'Declares an inline constant.',
    },
    {
        category: 'Variables',
        codeName: 'Var',
        dataType: '',
        description: 'Declares a reusable shader variable.',
    },
    {
        category: 'Variables',
        codeName: 'Const',
        dataType: '',
        description: 'Declares an inline constant.',
    },
    {
        category: 'Variables',
        codeName: 'property',
        dataType: '',
        description: 'Declares a property without initial value.',
    },
    {
        category: 'Varying',
        codeName: 'vertexStage',
        dataType: '',
        description: 'Computes a node in vertex stage, returns varying.',
    },
    {
        category: 'Varying',
        codeName: 'varying',
        dataType: '',
        description: 'Computes in vertex stage and passes interpolated value to fragment shader.',
    },
    {
        category: 'Varying',
        codeName: 'varyingProperty',
        dataType: '',
        description: 'Declares a varying property without initial value.',
    },
    {
        category: 'Conditional',
        codeName: 'If',
        dataType: '',
        description: 'If-Else control flow inside Fn().',
    },
    {
        category: 'Conditional',
        codeName: 'ElseIf',
        dataType: '',
        description: 'Else-if branch.',
    },
    {
        category: 'Conditional',
        codeName: 'Else',
        dataType: '',
        description: 'Else branch.',
    },
    {
        category: 'Conditional',
        codeName: 'select',
        dataType: '',
        description: 'Ternary outside of functions.',
    },
    {
        category: 'Loops',
        codeName: 'Loop',
        dataType: '',
        description: 'Supports counted, ranged, boolean, nested, and backward loops.',
    },
    {
        category: 'Loops',
        codeName: 'Break',
        dataType: '',
        description: 'Break loop execution.',
    },
    {
        category: 'Loops',
        codeName: 'Continue',
        dataType: '',
        description: 'Skip to next loop iteration.',
    },
    {
        category: 'MathFunctions',
        codeName: 'abs',
        dataType: '',
        description: 'Absolute value',
    },
    {
        category: 'MathFunctions',
        codeName: 'acos',
        dataType: '',
        description: 'Arccosine',
    },
    {
        category: 'MathFunctions',
        codeName: 'all',
        dataType: '',
        description: 'All components true',
    },
    {
        category: 'MathFunctions',
        codeName: 'any',
        dataType: '',
        description: 'Any component true',
    },
    {
        category: 'MathFunctions',
        codeName: 'asin',
        dataType: '',
        description: 'Arcsine',
    },
    {
        category: 'MathFunctions',
        codeName: 'atan',
        dataType: '',
        description: 'Arctangent',
    },
    {
        category: 'MathFunctions',
        codeName: 'bitcast',
        dataType: '',
        description: 'Reinterpret bits as different type',
    },
    {
        category: 'MathFunctions',
        codeName: 'cbrt',
        dataType: '',
        description: 'Cube root',
    },
    {
        category: 'MathFunctions',
        codeName: 'ceil',
        dataType: '',
        description: 'Round up',
    },
    {
        category: 'MathFunctions',
        codeName: 'clamp',
        dataType: '',
        description: 'Constrain between min and max',
    },
    {
        category: 'MathFunctions',
        codeName: 'cos',
        dataType: '',
        description: 'Cosine',
    },
    {
        category: 'MathFunctions',
        codeName: 'cross',
        dataType: '',
        description: 'Cross product',
    },
    {
        category: 'MathFunctions',
        codeName: 'dFdx',
        dataType: '',
        description: 'Partial derivative w.r.t. x',
    },
    {
        category: 'MathFunctions',
        codeName: 'dFdy',
        dataType: '',
        description: 'Partial derivative w.r.t. y',
    },
    {
        category: 'MathFunctions',
        codeName: 'degrees',
        dataType: '',
        description: 'Radians to degrees',
    },
    {
        category: 'MathFunctions',
        codeName: 'difference',
        dataType: '',
        description: 'Absolute difference',
    },
    {
        category: 'MathFunctions',
        codeName: 'distance',
        dataType: '',
        description: 'Distance between points',
    },
    {
        category: 'MathFunctions',
        codeName: 'dot',
        dataType: '',
        description: 'Dot product',
    },
    {
        category: 'MathFunctions',
        codeName: 'equals',
        dataType: '',
        description: 'Equality check',
    },
    {
        category: 'MathFunctions',
        codeName: 'exp',
        dataType: '',
        description: 'Natural exponentiation',
    },
    {
        category: 'MathFunctions',
        codeName: 'exp2',
        dataType: '',
        description: '2^x',
    },
    {
        category: 'MathFunctions',
        codeName: 'faceforward',
        dataType: '',
        description: 'Orient vector',
    },
    {
        category: 'MathFunctions',
        codeName: 'floor',
        dataType: '',
        description: 'Round down',
    },
    {
        category: 'MathFunctions',
        codeName: 'fract',
        dataType: '',
        description: 'Fractional part',
    },
    {
        category: 'MathFunctions',
        codeName: 'fwidth',
        dataType: '',
        description: 'Sum of abs derivatives in x and y',
    },
    {
        category: 'MathFunctions',
        codeName: 'inverseSqrt',
        dataType: '',
        description: '1 / sqrt(x)',
    },
    {
        category: 'MathFunctions',
        codeName: 'invert',
        dataType: '',
        description: '1 - x',
    },
    {
        category: 'MathFunctions',
        codeName: 'length',
        dataType: '',
        description: 'Vector length',
    },
    {
        category: 'MathFunctions',
        codeName: 'lengthSq',
        dataType: '',
        description: 'Squared vector length',
    },
    {
        category: 'MathFunctions',
        codeName: 'log',
        dataType: '',
        description: 'Natural log',
    },
    {
        category: 'MathFunctions',
        codeName: 'log2',
        dataType: '',
        description: 'Base-2 log',
    },
    {
        category: 'MathFunctions',
        codeName: 'max',
        dataType: '',
        description: 'Maximum of two values',
    },
    {
        category: 'MathFunctions',
        codeName: 'min',
        dataType: '',
        description: 'Minimum of two values',
    },
    {
        category: 'MathFunctions',
        codeName: 'mix',
        dataType: '',
        description: 'Linear interpolation',
    },
    {
        category: 'MathFunctions',
        codeName: 'negate',
        dataType: '',
        description: '-x',
    },
    {
        category: 'MathFunctions',
        codeName: 'normalize',
        dataType: '',
        description: 'Unit vector',
    },
    {
        category: 'MathFunctions',
        codeName: 'oneMinus',
        dataType: '',
        description: '1 - x',
    },
    {
        category: 'MathFunctions',
        codeName: 'pow',
        dataType: '',
        description: 'x^y',
    },
    {
        category: 'MathFunctions',
        codeName: 'pow2',
        dataType: '',
        description: 'x²',
    },
    {
        category: 'MathFunctions',
        codeName: 'pow3',
        dataType: '',
        description: 'x³',
    },
    {
        category: 'MathFunctions',
        codeName: 'pow4',
        dataType: '',
        description: 'x⁴',
    },
    {
        category: 'MathFunctions',
        codeName: 'radians',
        dataType: '',
        description: 'Degrees to radians',
    },
    {
        category: 'MathFunctions',
        codeName: 'reciprocal',
        dataType: '',
        description: '1 / x',
    },
    {
        category: 'MathFunctions',
        codeName: 'reflect',
        dataType: '',
        description: 'Reflection direction',
    },
    {
        category: 'MathFunctions',
        codeName: 'refract',
        dataType: '',
        description: 'Refraction direction',
    },
    {
        category: 'MathFunctions',
        codeName: 'round',
        dataType: '',
        description: 'Round to nearest integer',
    },
    {
        category: 'MathFunctions',
        codeName: 'saturate',
        dataType: '',
        description: 'Clamp between 0 and 1',
    },
    {
        category: 'MathFunctions',
        codeName: 'sign',
        dataType: '',
        description: 'Extract sign',
    },
    {
        category: 'MathFunctions',
        codeName: 'sin',
        dataType: '',
        description: 'Sine',
    },
    {
        category: 'MathFunctions',
        codeName: 'smoothstep',
        dataType: '',
        description: 'Hermite interpolation',
    },
    {
        category: 'MathFunctions',
        codeName: 'sqrt',
        dataType: '',
        description: 'Square root',
    },
    {
        category: 'MathFunctions',
        codeName: 'step',
        dataType: '',
        description: 'Step function',
    },
    {
        category: 'MathFunctions',
        codeName: 'tan',
        dataType: '',
        description: 'Tangent',
    },
    {
        category: 'MathFunctions',
        codeName: 'transformDirection',
        dataType: '',
        description: 'Transform direction and normalize',
    },
    {
        category: 'MathFunctions',
        codeName: 'trunc',
        dataType: '',
        description: 'Remove fractional part',
    },
];
